name: DomsCommands
description: Offers many commands for everyone to use!
main: com.domsplace.DomsCommands.DomsCommandsPlugin
authors: [Dominic, Jordan, Lazy, Kyle]
website: http://domsplace.com/
version: '1.00'
load: POSTWORLD
softdepend: []
commands:
   DomsCommands:
      description: Provides basic information about the DomsCommands plugin.
      aliases: [dcommands, domscom, doms]
      usage: /<command>
      permission: DomsCommands.domscommands
   donothing:
      description: Does nothing.
      usage: /<command>
      permission: DomsCommands.nothing
   motd:
      description: Allows a player to change the servers Message of the day.
      aliases: [setmotd]
      usage: /<command> [motd]
      permission: DomsCommands.motd
   shutdown:
      description: Allows a player to shutdown the server.
      aliases: [stop]
      usage: /<command> [message]
      permission: DomsCommands.shutdown
   teleportrequest:
      description: Sends a teleport request to the supplied player.
      aliases: [tpa, teleportto, teleportplease, tprequest]
      usage: /<command> [player]
      permission: DomsCommands.teleportrequest
   teleportrequesthere:
      description: Sends a teleport request to the supplied player.
      aliases: [tpah, tpahere, teleporthereplease, tphrequest]
      usage: /<command> [player]
      permission: DomsCommands.teleportrequesthere
   tpaccept:
      description: Accepts a Teleport Request Made by another player.
      aliases: [tpac, teleportaccept, teleportrequestaccept, tpyes]
      usage: /<command>
      permission: DomsCommands.tpaccept
   tpdeny:
      description: Denies a Teleport Request Made by another player.
      aliases: [tpno, tpn, tpd, tpden]
      usage: /<command>
      permission: DomsCommands.tpdeny
   back:
      description: Go Back to the last location you were at.
      aliases: [backwards]
      usage: /<command>
      permission: DomsCommands.back
   teleport:
      description: Teleport to a player.
      aliases: [tp, tpc, tpto, tpp, tpp2p, tptoplayer, tpplayer]
      usage: /<command> [player|coordinates] (player|coordinates)
      permission: DomsCommands.teleport
   teleporthere:
      description: Teleport another player to you.
      aliases: [tph, here]
      usage: /<command> [player]
      permission: DomsCommands.teleporthere
   teleportall:
      description: Teleport all players to a given player.
      aliases: [tpall, tpallhere]
      usage: /<command> (player)
      permission: DomsCommands.teleportall
   teleportrequestall:
      description: Teleport all players to a given player.
      aliases: [tprall, tprallhere, tpaall]
      usage: /<command> (player)
      permission: DomsCommands.teleportrequestall
   setwarp:
      description: Sets a warp where you're standing.
      aliases: [swarp, sw]
      usage: /<command> [name]
      permission: DomsCommands.setwarp
   deletewarp:
      description: Sets a warp where you're standing.
      aliases: [dwarp, delwarp, delwar, removewarp, rwarp]
      usage: /<command> [name]
      permission: DomsCommands.deletewarp
   warp:
      description: Warp to a previously set warp.
      aliases: [warps, listwarps]
      usage: /<command> (name|page)
      permission: DomsCommands.warp
   ban:
      description: Ban a player.
      aliases: [banish]
      usage: /<command> [player] (time) (reason)
      permission: DomsCommands.ban
   pardon:
      description: Unban a player and allow them back on the server.
      aliases: [unban, unbanish]
      usage: /<command> [player]
      permission: DomsCommands.pardon
   kick:
      description: Kicks a player from the server with an optional reason.
      aliases: [boot]
      usage: /<command> [player] (reason)
      permission: DomsCommands.kick
   away:
      description: Marks or unmarks yourself as being Away.
      aliases: [afk, awayfromkeyboard, busy]
      usage: /<command>
      permission: DomsCommands.away
   ping:
      description: Sends the message "Pong!" to the client.
      aliases: [pong]
      usage: /<command>
      permission: DomsCommands.ping
   nickname:
      description: Change the nickname of a player.
      aliases: [nick, setnick, setnickname]
      usage: /<command> (player) [nickname]
      permission: DomsCommands.nickname
   gamemode:
      description: Change yours or another players gamemode.
      aliases: [gm, creative, survival, adventure, gms, gmc, gma, gamemodecreative, gamemodec, gamemodesurvival, gamemodes, gamemodeadventure, gamemodea, togglegamemode, togglegm]
      usage: /<command> (player) (gamemode)
      permission: DomsCommands.gamemode
   tell:
      description: Send a private message to a player.
      aliases: [w, whisper, msg, message, talk, pm, pmessage, privatemessage, m]
      usage: /<command> [player] [message]
      permission: DomsCommands.tell
   reply:
      description: Send a reply.
      aliases: [r, respond]
      usage: /<command> [message]
      permission: DomsCommands.reply
   give:
      description: Give items to a player.
      aliases: [g, giveitem]
      usage: /<command> [player] [item(:data)] (amount)
      permission: DomsCommands.give
   getid:
      description: Gets information about the item in hand.
      aliases: [gid]
      usage: /<command> (item)
      permission: DomsCommands.getid
   time:
      description: Gets information about the item in hand.
      aliases: [day, night, morning, evening, midnigh, midday, fd, fixday]
      usage: /<command> (time) (world)
      permission: DomsCommands.time
   weather:
      description: Sets the weather of the world.
      aliases: [toggledownfall, toggledown, togglerain, togglestorm, sun, storm, rain, toggledf, thunder]
      usage: /<command> (weather) (world)
      permission: DomsCommands.weather
   item:
      description: Gives yourself an item.
      aliases: [i, get, getitem, giveme, want]
      usage: /<command> [item] (amount)
      permission: DomsCommands.item
permissions:
  # TODO: FINISH ALL THE * PERM NODES.
   DomsCommands.*:
     description: Gives access to all DomsCommands permissions.
     children:
       DomsChat.reload: true
   DomsCommands.reload:
     description: Allows access to reload the Configuration.
   DomsCommands.domscommands:
     description: Allows access to the DomsCommands command.
   DomsCommands.nothing:
     description: Allows access to the donothing command.
   DomsCommands.motd:
     description: Allows access to the motd command.
   DomsCommands.motd.set:
     description: Allows access to set the motd.
   DomsCommands.shutdown:
     description: Allows access to the shutdown command.
   DomsCommands.teleportrequest:
     description: Allows access to the teleportrequest command.
   DomsCommands.teleportrequesthere:
     description: Allows access to the teleportrequesthere command.
   DomsCommands.tpaccept:
     description: Allows access to the tpaccept command.
   DomsCommands.tpdeny:
     description: Allows access to the tpdeny command.
   DomsCommands.back:
     description: Allows access to the back command.
   DomsCommands.teleport:
     description: Allows access to the teleport command.
   DomsCommands.teleport.others:
     description: Allows players to teleport players to other players.
   DomsCommands.teleport.coordinates:
     description: Allows players to teleport to coordinates.
   DomsCommands.teleport.coordinates.others:
     description: Allows players to teleport other players to coordinates.
   DomsCommands.teleporthere:
     description: Allows access to the teleporthere command.
   DomsCommands.teleportall:
     description: Allows access to the teleportall command.
   DomsCommands.teleportrequestall:
     description: Allows access to the teleportrequestall command.
   DomsCommands.setwarp:
     description: Allows access to the setwarp command.
   DomsCommands.deletewarp:
     description: Allows access to the deletewarp command.
   DomsCommands.warp:
     description: Allows access to the warp command.
   DomsCommands.ban:
     description: Allows access to the ban command.
   DomsCommands.ban.notify:
     description: Shows a message when a player is banned.
   DomsCommands.ban.exempt:
     description: Makes a player exempt from being banned.
   DomsCommands.pardon:
     description: Allows access to the pardon command.
   DomsCommands.kick:
     description: Allows access to the kick command.
   DomsCommands.kick.exempt:
     description: Makes a player exempt from being kicked.
   DomsCommands.kick.notify:
     description: Shows a message when a player is kicked.
   DomsCommands.away:
     description: Allows access to the away command.
   DomsCommands.away.exempt:
     description: Blocks getting automatically kicked when Away.
   DomsCommands.ping:
     description: Allows access to the ping command.
   DomsCommands.nickname:
     description: Allows access to the nickname command.
   DomsCommands.nickname.colors.*:
     description: Allows access to use all colors in nicknames.
     children:
         DomsCommands.nickname.colors.black: true
         DomsCommands.nickname.colors.darkblue: true
         DomsCommands.nickname.colors.darkgreen: true
         DomsCommands.nickname.colors.cyan: true
         DomsCommands.nickname.colors.darkred: true
         DomsCommands.nickname.colors.purple: true
         DomsCommands.nickname.colors.gold: true
         DomsCommands.nickname.colors.gray: true
         DomsCommands.nickname.colors.darkgray: true
         DomsCommands.nickname.colors.green: true
         DomsCommands.nickname.colors.lightblue: true
         DomsCommands.nickname.colors.red: true
         DomsCommands.nickname.colors.pink: true
         DomsCommands.nickname.colors.yellow: true
         DomsCommands.nickname.colors.white: true
         DomsCommands.nickname.colors.magic: true
         DomsCommands.nickname.colors.bold: true
         DomsCommands.nickname.colors.strike: true
         DomsCommands.nickname.colors.underline: true
         DomsCommands.nickname.colors.italics: true
   DomsCommands.nickname.colors.black:
     description: Allows access to use black in nicknames.
   DomsCommands.nickname.colors.darkblue:
     description: Allows access to use darkblue in nicknames.
   DomsCommands.nickname.colors.darkgreen:
     description: Allows access to use darkgreen in nicknames.
   DomsCommands.nickname.colors.cyan:
     description: Allows access to use cyan in nicknames.
   DomsCommands.nickname.colors.darkred:
     description: Allows access to use darkred in nicknames.
   DomsCommands.nickname.colors.purple:
     description: Allows access to use purple in nicknames.
   DomsCommands.nickname.colors.gold:
     description: Allows access to use gold in nicknames.
   DomsCommands.nickname.colors.gray:
     description: Allows access to use gray in nicknames.
   DomsCommands.nickname.colors.darkgray:
     description: Allows access to use darkgray in nicknames.
   DomsCommands.nickname.colors.blue:
     description: Allows access to use blue in nicknames.
   DomsCommands.nickname.colors.green:
     description: Allows access to use green in nicknames.
   DomsCommands.nickname.colors.lightblue:
     description: Allows access to use lightblue in nicknames.
   DomsCommands.nickname.colors.red:
     description: Allows access to use red in nicknames.
   DomsCommands.nickname.colors.pink:
     description: Allows access to use pink in nicknames.
   DomsCommands.nickname.colors.yellow:
     description: Allows access to use yellow in nicknames.
   DomsCommands.nickname.colors.white:
     description: Allows access to use white in nicknames.
   DomsCommands.nickname.colors.magic:
     description: Allows access to use magic in nicknames.
   DomsCommands.nickname.colors.bold:
     description: Allows access to use bold in nicknames.
   DomsCommands.nickname.colors.strike:
     description: Allows access to use strike in nicknames.
   DomsCommands.nickname.colors.underline:
     description: Allows access to use underline in nicknames.
   DomsCommands.nickname.colors.italics:
     description: Allows access to use italics in nicknames.
   DomsCommands.gamemode:
     description: Allows access to the gamemode command.
   DomsCommands.tell:
     description: Allows access to the tell command.
   DomsCommands.tell.colors.*:
     description: Allows access to use all colors in messages.
     children:
         DomsCommands.tell.colors.black: true
         DomsCommands.tell.colors.darkblue: true
         DomsCommands.tell.colors.darkgreen: true
         DomsCommands.tell.colors.cyan: true
         DomsCommands.tell.colors.darkred: true
         DomsCommands.tell.colors.purple: true
         DomsCommands.tell.colors.gold: true
         DomsCommands.tell.colors.gray: true
         DomsCommands.tell.colors.darkgray: true
         DomsCommands.tell.colors.green: true
         DomsCommands.tell.colors.lightblue: true
         DomsCommands.tell.colors.red: true
         DomsCommands.tell.colors.pink: true
         DomsCommands.tell.colors.yellow: true
         DomsCommands.tell.colors.white: true
         DomsCommands.tell.colors.magic: true
         DomsCommands.tell.colors.bold: true
         DomsCommands.tell.colors.strike: true
         DomsCommands.tell.colors.underline: true
         DomsCommands.tell.colors.italics: true
   DomsCommands.tell.colors.black:
     description: Allows access to use black in messages.
   DomsCommands.tell.colors.darkblue:
     description: Allows access to use darkblue in messages.
   DomsCommands.tell.colors.darkgreen:
     description: Allows access to use darkgreen in messages.
   DomsCommands.tell.colors.cyan:
     description: Allows access to use cyan in messages.
   DomsCommands.tell.colors.darkred:
     description: Allows access to use darkred in messages.
   DomsCommands.tell.colors.purple:
     description: Allows access to use purple in messages.
   DomsCommands.tell.colors.gold:
     description: Allows access to use gold in messages.
   DomsCommands.tell.colors.gray:
     description: Allows access to use gray in messages.
   DomsCommands.tell.colors.darkgray:
     description: Allows access to use darkgray in messages.
   DomsCommands.tell.colors.blue:
     description: Allows access to use blue in messages.
   DomsCommands.tell.colors.green:
     description: Allows access to use green in messages.
   DomsCommands.tell.colors.lightblue:
     description: Allows access to use lightblue in messages.
   DomsCommands.tell.colors.red:
     description: Allows access to use red in messages.
   DomsCommands.tell.colors.pink:
     description: Allows access to use pink in messages.
   DomsCommands.tell.colors.yellow:
     description: Allows access to use yellow in messages.
   DomsCommands.tell.colors.white:
     description: Allows access to use white in messages.
   DomsCommands.tell.colors.magic:
     description: Allows access to use magic in messages.
   DomsCommands.tell.colors.bold:
     description: Allows access to use bold in messages.
   DomsCommands.tell.colors.strike:
     description: Allows access to use strike in messages.
   DomsCommands.tell.colors.underline:
     description: Allows access to use underline in messages.
   DomsCommands.tell.colors.italics:
     description: Allows access to use italics in messages.
   DomsCommands.reply:
     description: Allows access to the reply command.
   DomsCommands.give:
     description: Allows access to the give command.
   DomsCommands.getid:
     description: Allows access to the getid command.
   DomsCommands.time:
     description: Allows access to the time command.
   DomsCommands.weather:
     description: Allows access to the weather command.
   DomsCommands.item:
     description: Allows access to the item command.